apiVersion: v1
kind: Service
metadata:
  name: trade-svc
  namespace: trade
  labels:
    name: trade-brains
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: trade-brains-api
