apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Health_Check  On

  parsers.conf: |
    [PARSER]
        Name          json
        Format        json
        Time_Key      time
        Time_Format   %Y-%m-%d %H:%M:%S
        Time_Keep     On
