name: Trade_App_Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev
env:
  environment: development
jobs:

  build:
    name: Build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_USERNAME }}
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_ready

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: check files
      run: ls

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.2'

    - name: install dependencies
      run: |
        pip install -r requirements.txt

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: check files
      run: ls

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.2'

    - name: install dependencies
      run: |
        pip install -r requirements.txt

    - name: make tests
      run: |
        python manage.py trade_root.company.tests
        python manage.py trade_root.users.tests
        python manage.py trade_root.watchlist.tests
