version: '3'
services:
  app:
    image: ''
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - docker.env
  redis:
    image: redis
    ports:
      - "6379:6479"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - postgres_data:/vara/lib/postgresql/data
volumes:
  postgres_data:
  redis_data: