version: '3'
services:
  app:
    image: luciferro10/trade-app:dev
    build:
      context: .
    ports:
    - "8000:8000"
    env_file:
    - docker.env
    depends_on:
    - db
    - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis:
    image: redis
    ports:
    - "6379:6479"
    volumes:
    - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      intervals: 10s
      timeout: 5s
      retries: 2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  db:
    image: postgres
    ports:
    - "5432:5432"
    env_file:
    - docker.env
    volumes:
    - postgres_data:/vara/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  postgres_data:
  redis_data:
