# Generated by Django 5.2.5 on 2025-08-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'company_info', 'verbose_name_plural': 'company_infos'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='company.company'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['companyy_name'], name='company_name_idx'),
        ),
    ]
