# Generated by Django 5.2.5 on 2025-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
